### ISSUE TITLE
How to get regression equation?

### ISSUE THREAD

**Issue by Gyagupta** [ngupta23/ngupta23#5]
Please help driving the final regression equation after belnding of top 3 models in PyCaret!!

**Comment by ngupta23** [comment]
Please file in the pycaret repo.

**Comment by Gyagupta** [comment]
please can you help in this matter where to file, i am new to the community and do not understand all the things in this!!

**Comment by ngupta23** [comment]
https://github.com/pycaret/pycaret/issues
